In [1]:
from data import load_normalized_dataset, extract_features
import pandas, numpy

In [5]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

In [2]:
df = load_normalized_dataset()

Attempting to load normalized dataset...
Returning normalized dataset.

In [3]:
df.head(10)

,IDNew,SocialNetwork,SenderUserId,FollowersCount,Message,CreatedTime,MessageType,NormalizedMessage
0,4.158647e+09,TWITTER,1.150201e+18,99,Hey @NavyFederalHelp @NavyFederal are you guys...,2020-01-30 19:09:07.795,Twitter Mention,hey are you guys compatible with the security ...
1,4.158647e+09,TWITTER,1.150201e+18,99,Hey @NavyFederalHelp @NavyFederal are you guys...,2020-01-30 19:09:07.795,Twitter Mention,hey are you guys compatible with the security ...
2,4.131474e+09,TWITTER,8.765216e+17,407,@NavyFederal You’re welcome. Tons of locals wi...,2020-01-30 19:07:55.126,Twitter Reply,you are welcome tons of locals with nf in the ...
3,4.131474e+09,TWITTER,8.765216e+17,407,@NavyFederal please put a location in Daytona ...,2020-01-30 19:01:02.803,Twitter Mention,please put a location in daytona thanks
4,2.066183e+09,TWITTER,9.404094e+08,1079,@NavyFederal i’m bout SICK of yall.,2020-01-30 17:53:31.435,Twitter Mention,i am bout sick of yall
5,2.110529e+09,TWITTER,1.465241e+09,109125,Davide Moretti drove his way through the lane ...,2020-01-30 17:20:00.257,Twitter Mention,davide moretti drove his way through the lane ...
6,1.985451e+09,TWITTER,4.194737e+08,3755,@TheNCUA how is it @NavyFederal can disable a...,2020-01-30 17:09:14.505,Twitter Mention,how is it can disable all tabs and disable my ...
7,4.162829e+09,TWITTER,1.199326e+18,1,@defenseupdate @IDFSpokesperson @chicagoGDC @H...,2020-01-30 17:00:29.424,Twitter Mention,defense apac pga
8,1.985451e+09,TWITTER,4.194737e+08,3755,Gee Navy Federal Is A Bank Of Be Best Aint it ...,2020-01-30 17:00:11.694,Twitter Mention,gee navy federal is a bank of be best aint it ...
9,1.958612e+09,TWITTER,3.207328e+08,993,@mac_10k @NavyFederal We good here. Thanks but...,2020-01-30 16:37:24.573,Twitter Mention,k we good here thanks but no thanks

In [4]:
# Most common words

doc_term_mat, co_occ_mat, count_vec = extract_features(df.NormalizedMessage.astype(str))
#numpy.shape(doc_term_mat.sum(axis=0))
top_term_freqs = pandas.DataFrame(
    columns=['token', 'freq'],
    data={
        'token': count_vec.get_feature_names(),
        'freq': numpy.array(doc_term_mat.sum(axis=0))[0]
        }
)
top_term_freqs.sort_values(by='freq', ascending=False).head(10)

    token   freq
884    to  82770
864   the  78754
996   you  71146
40    and  64842
314   for  62277
433    is  52650
578   not  42365
374  have  39952
418    in  38438
436    it  36746

In [5]:
# Most common words filtering out stopwords

doc_term_mat, co_occ_mat, count_vec = extract_features(df.NormalizedMessage.astype(str), stop_words=stop_words)
#numpy.shape(doc_term_mat.sum(axis=0))
top_term_freqs = pandas.DataFrame(
    columns=['token', 'freq'],
    data={
        'token': count_vec.get_feature_names(),
        'freq': numpy.array(doc_term_mat.sum(axis=0))[0]
        }
)
top_term_freqs.sort_values(by='freq', ascending=False).head(100)

           token   freq
566         navy  26815
928           us  20573
192       credit  19263
292      federal  18108
984        would  17613
879       thanks  17053
158          com  16362
341          get  15513
467         like  15243
4        account  14594
652       please  14004
915      twitter  13982
878        thank  13069
447         know  12024
889         time  12016
108         call  12011
922        union  11697
603          one  10506
550        money  10315
116         card   9968
570         need   9820
382         help   9743
578         nfcu   9325
494         love   8696
74          bank   8662
787      service   8543
117        cards   8089
563          nan   7581
83          best   7445
643          pic   7414
..           ...    ...
184        could   4913
605       online   4913
948         want   4905
29          also   4890
422         info   4795
263         even   4756
806        since   4718
206          day   4676
856         sure   4628
892        today   4584
952          way   4562
30        always   4496
670      private   4436
423  information   4434
702     reaching   4418
0           able   4349
440         keep   4343
5       accounts   4315
747        right   4286
54          army   4266
538     military   4262
517          may   4221
196     customer   4206
75       banking   4142
977         work   4095
960         well   4087
67     available   4045
273   experience   3920
508         many   3886
559         much   3850

[100 rows x 2 columns]

In [6]:
#Most frequent bigrams filtering out stopwords

doc_term_mat, co_occ_mat, count_vec = extract_features(df.NormalizedMessage.astype(str), stop_words=stop_words, ngram_range=(2,2))
#numpy.shape(doc_term_mat.sum(axis=0))
top_term_freqs = pandas.DataFrame(
    columns=['token', 'freq'],
    data={
        'token': count_vec.get_feature_names(),
        'freq': numpy.array(doc_term_mat.sum(axis=0))[0]
        }
)
top_term_freqs.sort_values(by='freq', ascending=False).head(100)

                token   freq
553      navy federal  17282
899       twitter com  13686
199      credit union  11538
269    federal credit   7409
652       pic twitter   7255
978        would like   6326
140     cards twitter   5088
170         com cards   5087
139         cards egq   5065
388       hey rooting   4975
685   private message   3949
924           us know   3799
870   thanks reaching   3662
193       credit card   3377
476        loud proud   3296
158     cheering loud   3294
752           send us   3215
442            let us   3208
201  customer service   2952
930        us private   2822
728      rooting navy   2769
549        navy cards   2751
670       please send   2734
116           call us   2428
689  proud midshipmen   2340
918           us call   2309
727      rooting army   2295
62         army cards   2282
552          navy fed   2244
330           give us   2032
..                ...    ...
457         like take    923
825         take look    917
626       org contact    881
423        kind words    861
481         love nfcu    854
475        looks like    851
881        time reach    850
155  checking account    836
198      credit score    832
507      member since    829
288    following link    823
658      please email    822
365    great question    817
431        know would    811
339         god bless    789
879         time call    787
280         feel free    787
345         good luck    781
233      email nfhelp    776
337           go navy    765
25   account specific    738
979        would love    732
430    know questions    726
851        thank much    714
857     thank sharing    714
632        pass along    710
747         semper fi    704
491        many years    695
691       proud serve    694
508      member years    690

[100 rows x 2 columns]

In [7]:
#Most frequent trigrams filtering out stopwords

doc_term_mat, co_occ_mat, count_vec = extract_features(df.NormalizedMessage.astype(str), stop_words=stop_words, ngram_range=(3,3))
#numpy.shape(doc_term_mat.sum(axis=0))
top_term_freqs = pandas.DataFrame(
    columns=['token', 'freq'],
    data={
        'token': count_vec.get_feature_names(),
        'freq': numpy.array(doc_term_mat.sum(axis=0))[0]
        }
)
top_term_freqs.sort_values(by='freq', ascending=False).head(100)

                        token  freq
628           pic twitter com  7255
546       navy federal credit  7248
262      federal credit union  7221
123         cards twitter com  5088
883         twitter com cards  5086
145             com cards egq  5065
134       cheering loud proud  3294
912        us private message  2814
538        navy cards twitter  2750
727        rooting navy cards  2744
360          hey rooting navy  2713
435               let us know  2647
749           send us private  2624
473     loud proud midshipmen  2340
49         army cards twitter  2281
726        rooting army cards  2270
359          hey rooting army  2258
649            please send us  2207
315              give us call  1747
644             please let us  1355
854        thanks reaching us  1335
158       contact number best  1198
579          number best time  1196
436           letting us know  1167
630            please call us  1144
477         love navy federal  1143
640            please give us  1070
40            apac defense wi  1051
390         info social media   955
474          loud proud notre   954
..                        ...   ...
831           team would like   472
983          would like speak   469
989             would like us   430
452          like take deeper   429
201    deeper look experience   418
848         thanks kind words   417
583          number two three   410
33      american express card   383
888       two three preferred   382
160        contact number two   381
844    thank sharing concerns   375
719  rewards american express   372
355          help please send   368
138      click following link   359
289      forward serving many   355
580         number best times   351
623         phone number best   346
569          never doubt navy   345
841        thank navy federal   344
467     look forward speaking   340
451          like take closer   332
976           would like look   330
863     three preferred times   320
558      navy federal rewards   317
75          best credit union   316
835    terrorist ceo blogspot   313
314         ght terrorist ceo   313
703   replied private message   311
492           many years come   310
982          would like share   310

[100 rows x 2 columns]

In [6]:
# Most common cooccurs filtering out stopwords

doc_term_mat, co_occ_mat, count_vec = extract_features(df.NormalizedMessage.astype(str), stop_words=stop_words)

tokens = count_vec.get_feature_names()
cofreq_terms = [(x,y) for x in tokens for y in tokens]
cofreq = []
top_term_cofreqs = pandas.DataFrame(columns=['tokens', 'cofreq'], data={
    'tokens': cofreq_terms,
    'cofreq': [co_occ_mat[count_vec.vocabulary_[x],count_vec.vocabulary_[y]] for (x,y) in cofreq_terms]
})

In [9]:
def load_subjectivity_lexicon():
    posUrl, negUrl = "../resources/sentiment_lexicon/positive-words.txt", "../resources/sentiment_lexicon/negative-words.txt"
    with open(posUrl, "r") as posFile, open(negUrl, "r") as negFile:
        posText, negText = posFile.read(), negFile.read()
        posLines, negLines = posText.split("\n"), negText.split("\n")
        return posLines[31:], negLines[31:]

In [29]:
positive_tokens, negative_tokens = load_subjectivity_lexicon()

In [1]:
import lda2vec

ModuleNotFoundError: No module named 'lda2vec'